cognito.user-pool-id=us-east-1_Y3AVPF7cE
cognito.client-id=6m496adbmi95ln3i1pta9tnj9s
cognito.client-secret=126hu4uafeurrdld6c1ofnu0tpjeiprmuasofdnvf6vd9ae72bsu
cognito.region=us-east-1

quarkus.oidc.auth-server-url=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Y3AVPF7cE
quarkus.oidc.client-id=6m496adbmi95ln3i1pta9tnj9s
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Y3AVPF7cE
quarkus.oidc.roles.role-claim-path=cognito:groups

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/teleticketlite
quarkus.hibernate-orm.log.sql=false

quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=ASIAU6GDYID5QRS3PU37
quarkus.s3.aws.credentials.static-provider.secret-access-key=Q3MsQ7s8yXKl0v7lp4uDZE4j4xOObWdTfpN0JszV
s3.bucket-name=teleticket-lite-images