cognito.user-pool-id=us-east-1_Y3AVPF7cE
cognito.client-id=6m496adbmi95ln3i1pta9tnj9s
cognito.client-secret=126hu4uafeurrdld6c1ofnu0tpjeiprmuasofdnvf6vd9ae72bsu

quarkus.oidc.auth-server-url=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Y3AVPF7cE
quarkus.oidc.client-id=6m496adbmi95ln3i1pta9tnj9s
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=https://cognito-idp.us-east-1.amazonaws.com/6m496adbmi95ln3i1pta9tnj9s
quarkus.oidc.roles.role-claim-path=cognito:groups