cognito.user-pool-id=
cognito.client-id=
cognito.client-secret=
cognito.region=us-east-1

quarkus.oidc.auth-server-url=https://cognito-idp.us-east-1.amazonaws.com/
quarkus.oidc.client-id=
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=https://cognito-idp.us-east-1.amazonaws.com/
quarkus.oidc.roles.role-claim-path=cognito:groups

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/teleticketlite
quarkus.hibernate-orm.log.sql=false

quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=
quarkus.s3.aws.credentials.static-provider.secret-access-key=

aws.credentials.access-key-id=
aws.credentials.secret-access-key=
s3.bucket-name=teleticket-lite-images-561547870320